"""add locations and user context

Revision ID: 1a4775510f4b
Revises: 584e5797dd80
Create Date: 2026-01-28 20:08:04.136215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4775510f4b'
down_revision: Union[str, Sequence[str], None] = '584e5797dd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    
    op.create_table('cities',
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('city_id'),
    sa.UniqueConstraint('city_name'),
    schema='locations'
    )
    
    op.create_table('campuses',
    sa.Column('campus_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('campus_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['locations.cities.city_id'], ),
    sa.PrimaryKeyConstraint('campus_id'),
    schema='locations'
    )
    
    op.create_table('buildings',
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=False),
    sa.Column('building_name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['locations.campuses.campus_id'], ),
    sa.PrimaryKeyConstraint('building_id'),
    schema='locations'
    )
    
    op.create_table('cafe_branch',
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('cafe_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['locations.buildings.building_id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['locations.campuses.campus_id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['locations.cities.city_id'], ),
    sa.PrimaryKeyConstraint('branch_id'),
    schema='core'
    )
    op.create_table('user_context',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['locations.buildings.building_id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['locations.campuses.campus_id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['locations.cities.city_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_context', schema='core')
    op.drop_table('cafe_branch', schema='core')
    op.drop_table('payment_attempts', schema='payments')
    op.drop_table('buildings', schema='locations')
    op.drop_table('payment_intents', schema='payments')
    op.drop_table('order_status_logs', schema='orders')
    op.drop_table('order_items', schema='orders')
    op.drop_table('campuses', schema='locations')
    op.drop_table('staff', schema='core')
    op.drop_table('role_permissions', schema='core')
    op.drop_table('menu_items', schema='catalog')
    op.drop_table('orders', schema='orders')
    op.drop_table('cart_items', schema='orders')
    op.drop_table('cart', schema='orders')
    op.drop_table('cities', schema='locations')
    op.drop_table('users', schema='core')
    op.drop_table('user_addresses', schema='core')
    op.drop_table('staff_roles', schema='core')
    op.drop_table('signup_sessions', schema='core')
    op.drop_table('permissions', schema='core')
    op.drop_table('notifications', schema='core')
    op.drop_table('cafeteria', schema='core')
    op.drop_table('menu_categories', schema='catalog')
    op.drop_table('item_types', schema='catalog')
    op.drop_table('branch_menu_items', schema='catalog')
    # ### end Alembic commands ###
