"""add missing catalog tables

Revision ID: 4f0f5ea1fc11
Revises: b84e4040cf73
Create Date: 2026-01-22 21:04:04.912673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0f5ea1fc11'
down_revision: Union[str, Sequence[str], None] = 'b84e4040cf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('item_types',
    sa.Column('item_type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('item_type_id'),
    sa.UniqueConstraint('name'),
    schema='catalog'
    )
    
    
    
    
    
    
    
   
   
    
    
   
    
   
   
    
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_attempts', schema='payments')
    op.drop_table('payment_intents', schema='payments')
    op.drop_table('order_status_logs', schema='orders')
    op.drop_table('order_items', schema='orders')
    op.drop_table('staff', schema='core')
    op.drop_table('role_permissions', schema='core')
    op.drop_table('menu_items', schema='catalog')
    op.drop_table('orders', schema='orders')
    op.drop_table('cart_items', schema='orders')
    op.drop_table('cart', schema='orders')
    op.drop_table('users', schema='core')
    op.drop_table('user_addresses', schema='core')
    op.drop_table('staff_roles', schema='core')
    op.drop_table('permissions', schema='core')
    op.drop_table('notifications', schema='core')
    op.drop_table('cafeteria', schema='core')
    op.drop_table('cafe_branch', schema='core')
    op.drop_table('menu_categories', schema='catalog')
    op.drop_table('item_types', schema='catalog')
    op.drop_table('branch_menu_items', schema='catalog')
    # ### end Alembic commands ###
