"""add signup session table

Revision ID: 584e5797dd80
Revises: f40e6d64a3f6
Create Date: 2026-01-28 10:14:20.897431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584e5797dd80'
down_revision: Union[str, Sequence[str], None] = 'f40e6d64a3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('signup_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_attempts', schema='payments')
    op.drop_table('payment_intents', schema='payments')
    op.drop_table('order_status_logs', schema='orders')
    op.drop_table('order_items', schema='orders')
    op.drop_table('staff', schema='core')
    op.drop_table('role_permissions', schema='core')
    op.drop_table('menu_items', schema='catalog')
    op.drop_table('orders', schema='orders')
    op.drop_table('cart_items', schema='orders')
    op.drop_table('cart', schema='orders')
    op.drop_table('users', schema='core')
    op.drop_table('user_addresses', schema='core')
    op.drop_table('staff_roles', schema='core')
    op.drop_table('signup_sessions', schema='core')
    op.drop_table('permissions', schema='core')
    op.drop_table('notifications', schema='core')
    op.drop_table('cafeteria', schema='core')
    op.drop_table('cafe_branch', schema='core')
    op.drop_table('menu_categories', schema='catalog')
    op.drop_table('item_types', schema='catalog')
    op.drop_table('branch_menu_items', schema='catalog')
    # ### end Alembic commands ###
