"""initial schema

Revision ID: b84e4040cf73
Revises: 
Create Date: 2026-01-22 20:25:30.326034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84e4040cf73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS catalog")
    op.execute("CREATE SCHEMA IF NOT EXISTS orders")
    op.execute("CREATE SCHEMA IF NOT EXISTS payments")
    op.execute("CREATE SCHEMA IF NOT EXISTS locations")
    

    op.create_table('branch_menu_items',
    sa.Column('branch_menu_item_id', sa.BigInteger(), nullable=False),
    sa.Column('cafe_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('branch_menu_item_id'),
    schema='catalog'
    )
    op.create_table('menu_categories',
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('cafe_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('category_description', sa.String(), nullable=True),
    sa.Column('category_image', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    schema='catalog'
    )
    op.create_table('menu_items',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('item_type_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('item_id'),
    schema='catalog'
    )
    op.create_table('cafe_branch',
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('cafe_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('branch_id'),
    schema='core'
    )
    op.create_table('cafeteria',
    sa.Column('cafe_id', sa.BigInteger(), nullable=False),
    sa.Column('cafe_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cafe_id'),
    schema='core'
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.Enum('STAFF', 'USER', name='notification_recipient'), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('related_order_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_code'),
    schema='core'
    )
    op.create_table('staff_roles',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=True),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    schema='core'
    )
    op.create_table('user_addresses',
    sa.Column('address_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('address_line_1', sa.String(), nullable=True),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('address_id'),
    schema='core'
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('is_otp_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('mobile_number'),
    schema='core'
    )
    op.create_table('cart',
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cart_id'),
    schema='orders'
    )
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.BigInteger(), nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('cart_item_id'),
    schema='orders'
    )
    op.create_table('orders',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_status', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('repeat_weekly', sa.Boolean(), nullable=False),
    sa.Column('repeat_remaining', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True),server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True),server_default=sa.text('now()'), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('order_id'),
    schema='orders'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['core.permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['core.staff_roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='core'
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True),server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['core.staff_roles.role_id'], ),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('username'),
    schema='core'
    )
    op.create_table('order_items',
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id'),
    schema='orders'
    )
    op.create_table('order_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.String(length=20), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True),server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_table('payment_intents',
    sa.Column('intent_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True),server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intent_id'),
    sa.UniqueConstraint('order_id'),
    schema='payments'
    )
    op.create_table('payment_attempts',
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('intent_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_payment_id', sa.BigInteger(), nullable=True),
    sa.Column('gateway', sa.String(length=20), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True),server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True),server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['payments.payment_intents.intent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_payment_id'], ['payments.payment_attempts.attempt_id'], ),
    sa.PrimaryKeyConstraint('attempt_id'),
    sa.UniqueConstraint('gateway_transaction_id'),
    schema='payments'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_attempts', schema='payments')
    op.drop_table('payment_intents', schema='payments')
    op.drop_table('order_status_logs', schema='orders')
    op.drop_table('order_items', schema='orders')
    op.drop_table('staff', schema='core')
    op.drop_table('role_permissions', schema='core')
    op.drop_table('orders', schema='orders')
    op.drop_table('cart_items', schema='orders')
    op.drop_table('cart', schema='orders')
    op.drop_table('users', schema='core')
    op.drop_table('user_addresses', schema='core')
    op.drop_table('staff_roles', schema='core')
    op.drop_table('permissions', schema='core')
    op.drop_table('notifications', schema='core')
    op.drop_table('cafeteria', schema='core')
    op.drop_table('cafe_branch', schema='core')
    op.drop_table('menu_items', schema='catalog')
    op.drop_table('menu_categories', schema='catalog')
    op.drop_table('branch_menu_items', schema='catalog')
    # ### end Alembic commands ###
