"""added location-support vendor

Revision ID: f40e6d64a3f6
Revises: 4f0f5ea1fc11
Create Date: 2026-01-27 22:22:27.864919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40e6d64a3f6'
down_revision: Union[str, Sequence[str], None] = '4f0f5ea1fc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column(
        "cafe_branch",
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        schema="core",
    )

    op.create_foreign_key(
        "fk_cafe_branch_city",
        source_table="cafe_branch",
        referent_table="cities",
        local_cols=["city_id"],
        remote_cols=["city_id"],
        source_schema="core",
        referent_schema="locations",
    )


    op.add_column(
        "cafe_branch",
        sa.Column("campus_id", sa.BigInteger(), nullable=False),
        schema="core",
    )

    op.create_foreign_key(
        "fk_cafe_branch_campus",
        source_table="cafe_branch",
        referent_table="campuses",
        local_cols=["campus_id"],
        remote_cols=["campus_id"],
        source_schema="core",
        referent_schema="locations",
    )


    op.add_column(
        "cafe_branch",
        sa.Column("building", sa.BigInteger(), nullable=False),
        schema="core",
    )

    op.create_foreign_key(
        "fk_cafe_branch_building",
        source_table="cafe_branch",
        referent_table="buildings",
        local_cols=["building_id"],
        remote_cols=["building_id"],
        source_schema="core",
        referent_schema="locations",
    )

    
    op.add_column(
        "cafe_branch",
        sa.Column("latitude", sa.Float(), nullable=True),
        schema="core",
    )
    op.add_column(
        "cafe_branch",
        sa.Column("longitude", sa.Float(), nullable=True),
        schema="core",
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_attempts', schema='payments')
    op.drop_table('payment_intents', schema='payments')
    op.drop_table('order_status_logs', schema='orders')
    op.drop_table('order_items', schema='orders')
    op.drop_table('staff', schema='core')
    op.drop_table('role_permissions', schema='core')
    op.drop_table('menu_items', schema='catalog')
    op.drop_table('orders', schema='orders')
    op.drop_table('cart_items', schema='orders')
    op.drop_table('cart', schema='orders')
    op.drop_table('users', schema='core')
    op.drop_table('user_addresses', schema='core')
    op.drop_table('staff_roles', schema='core')
    op.drop_table('permissions', schema='core')
    op.drop_table('notifications', schema='core')
    op.drop_table('cafeteria', schema='core')
    op.drop_table('cafe_branch', schema='core')
    op.drop_table('menu_categories', schema='catalog')
    op.drop_table('item_types', schema='catalog')
    op.drop_table('branch_menu_items', schema='catalog')
    # ### end Alembic commands ###
