class Permission:
    VIEW_ORDERS = "VIEW_ORDERS"
    ACCEPT_ORDER = "ACCEPT_ORDER"
    REJECT_ORDER = "REJECT_ORDER"
    MOVE_ORDER = "MOVE_ORDER"

    MANAGE_MENU = "MANAGE_MENU"
    MANAGE_STAFF = "MANAGE_STAFF"
